### ISSUE TITLE
IndexError: Target 46 is out of bounds.

### ISSUE THREAD

**Issue by Lixinyoung** [GlancerZ/scCobra#1]
I have followed the tutorial to integrate my data that have 66 batch. When I run "Second step training" part, an error "IndexError: Target 46 is out of bounds" raised. I change no code. By the way, I have to manually change the [R_HOME] path in "preprocess.py". Thank you for your tools and looking forward an answer!
`IndexError                                Traceback (most recent call last)
Cell In [15], line 24
     20 optimizer_d.zero_grad()
     22 z, h1, h2 = encoder_model(x,y)
---> 24 loss_d = dis_model(z,y)            
     26 sum_d += loss_d.item()
     28 loss_d.backward()

File ~/miniconda3/envs/scCobra/lib/python3.8/site-packages/torch/nn/modules/module.py:1190, in Module._call_impl(self, *input, **kwargs)
   1186 # If we don't have any hooks, we want to skip the rest of the logic in
   1187 # this function, and just call forward.
   1188 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1189         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1190     return forward_call(*input, **kwargs)
   1191 # Do not call functions when jit is used
   1192 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniconda3/envs/scCobra/lib/python3.8/sccobra/model.py:98, in discriminator.forward(self, x, label)
     94 def forward(self, x, label):
     96     output = self.net(x)
---> 98     loss = self.loss(output, label.long())
    100     return loss

File ~/miniconda3/envs/scCobra/lib/python3.8/site-packages/torch/nn/modules/module.py:1190, in Module._call_impl(self, *input, **kwargs)
   1186 # If we don't have any hooks, we want to skip the rest of the logic in
   1187 # this function, and just call forward.
   1188 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1189         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1190     return forward_call(*input, **kwargs)
   1191 # Do not call functions when jit is used
   1192 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniconda3/envs/scCobra/lib/python3.8/sccobra/model.py:78, in LabelSmoothingCrossEntropy.forward(self, output, target)
     76     if self.reduction=='mean':
     77         loss = loss.mean()
---> 78 return loss*self.eps/c + (1-self.eps) * F.nll_loss(log_preds, target, reduction=self.reduction)

File ~/miniconda3/envs/scCobra/lib/python3.8/site-packages/torch/nn/functional.py:2701, in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2699 if size_average is not None or reduce is not None:
   2700     reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2701 return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

IndexError: Target 46 is out of bounds.`

**Comment by GlancerZ** [comment]
In my view, if you can finish the first step, the second step should correct. Would you plot the batch integration results of first step here?

**Comment by Lixinyoung** [comment]
> In my view, if you can finish the first step, the second step should correct. Would you plot the batch integration results of first step here?

![image](https://user-images.githubusercontent.com/76689104/202859441-61b556aa-2deb-4345-b6ca-bd2fb6c24169.png)

"visualization of pretraining results" step can be accomplished.

**Comment by GlancerZ** [comment]
OK, I know. I give a permanent number at discriminator function, I have fixed it. You can redefine the discriminator follow the new tutorial.

**Comment by Lixinyoung** [comment]
The issue seemed to get fixed! Thank you for your response.
